version: "3.8"
services:
  nginx:
    #build: .
    container_name: "nginx-container"
    ports:
      - "5000:5000"
    depends_on:
      - gunicorn-flask
  gunicorn-flask:
    build: gunicorn-pythonflask
    container_name: "gunicorn-pythonflask-container"
